defmodule PolskaTest do
  use ExUnit.Case
  doctest Polska

  test "number correctness" do
    assert Polska.print("0")	==	"zero"
    assert Polska.print("1")	==	"jeden"
    assert Polska.print("2")	==	"dwa"
    assert Polska.print("3")	==	"trzy"
    assert Polska.print("4")	==	"cztery"
    assert Polska.print("5")	==	"pięć"
    assert Polska.print("6")	==	"sześć"
    assert Polska.print("7")	==	"siedem"
    assert Polska.print("8")	==	"osiem"
    assert Polska.print("9")	==	"dziewięć"
    assert Polska.print("10")	==	"dziesięć"
    assert Polska.print("11")	==	"jedenaście"
    assert Polska.print("12")	==	"dwanaście"
    assert Polska.print("13")	==	"trzynaście"
    assert Polska.print("14")	==	"czternaście"
    assert Polska.print("15")	==	"piętnaście"
    assert Polska.print("16")	==	"szesnaście"
    assert Polska.print("17")	==	"siedemnaście"
    assert Polska.print("18")	==	"osiemnaście"
    assert Polska.print("19")	==	"dziewiętnaście"
    assert Polska.print("20")	==	"dwadzieścia"
    assert Polska.print("21")	==	"dwadzieścia jeden"
    assert Polska.print("22")	==	"dwadzieścia dwa"
    assert Polska.print("23")	==	"dwadzieścia trzy"
    assert Polska.print("24")	==	"dwadzieścia cztery"
    assert Polska.print("25")	==	"dwadzieścia pięć"
    assert Polska.print("26")	==	"dwadzieścia sześć"
    assert Polska.print("27")	==	"dwadzieścia siedem"
    assert Polska.print("28")	==	"dwadzieścia osiem"
    assert Polska.print("29")	==	"dwadzieścia dziewięć"
    assert Polska.print("30")	==	"trzydzieści"
    assert Polska.print("40")	==	"czterdzieści"
    assert Polska.print("50")	==	"pięćdziesiąt"
    assert Polska.print("60")	==	"sześćdziesiąt"
    assert Polska.print("70")	==	"siedemdziesiąt"
    assert Polska.print("80")	==	"osiemdziesiąt"
    assert Polska.print("90")	==	"dziewięćdziesiąt"
    assert Polska.print("100")	==	"sto"
    assert Polska.print("200")	==	"dwieście"
    assert Polska.print("300")	==	"trzysta"
    assert Polska.print("400")	==	"czterysta"
    assert Polska.print("500")	==	"pięćset"
    assert Polska.print("600")	==	"sześćset"
    assert Polska.print("700")	==	"siedemset"
    assert Polska.print("800")	==	"osiemset"
    assert Polska.print("900")	==	"dziewięćset"
    assert Polska.print("1000")	==	"tysiąc"
    assert Polska.print("2000")	==	"dwa tysiące"
    assert Polska.print("3000")	==	"trzy tysiące"
    assert Polska.print("4000")	==	"cztery tysiące"
    assert Polska.print("5000")	==	"pięć tysięcy"
    assert Polska.print("6000")	==	"sześć tysięcy"
    assert Polska.print("7000")	==	"siedem tysięcy"
    assert Polska.print("8000")	==	"osiem tysięcy"
    assert Polska.print("9000")	==	"dziewięć tysięcy"
    assert Polska.print("10000")	==	"dziesięć tysięcy"
    assert Polska.print("1000000")	==	"milion"
    assert Polska.print("2000000")	==	"dwa miliony"
    assert Polska.print("1000000000")	==	"miliard"
    assert Polska.print("2000000000")	==	"dwa miliardy"
    assert Polska.print("1000000000000")	==	"bilion"
    assert Polska.print("2000000000000")	==	"dwa biliony"
    assert Polska.print("1000000000000000")	==	"biliard"
    assert Polska.print("2000000000000000")	==	"dwa biliardy"
    assert Polska.print("123456789")	==	"sto dwadzieścia trzy miliony czterysta pięćdziesiąt sześć tysięcy siedemset osiemdziesiąt dziewięć"
  end
end
